# vim:fileencoding=utf-7:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#cfc251" }

# Hovered
hovered         = { fg = "#000000", bg = "#ac9259" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#b32121", italic = true }
find_position = { fg = "#e6a0b3", bg = "#3d4a45", italic = true }

# Marker
marker_selected = { fg = "#e6a0b3",  bg = "#e6a0b3" }
marker_copied   = { fg = "#8bca4b", bg = "#8bca4b" }
marker_cut      = { fg = "#ea6962",    bg = "#ea6962" }
marker_marked   = { fg = "#71acc8", bg = "#71acc8" }

# Tab
tab_active   = { fg = "#000000", bg = "#cfc251" }
tab_inactive = { fg = "#D1BF93", bg = "#3c3937" }
tab_width    = 1

# Count
count_copied   = { fg = "#000000", bg = "#8bca4b" }
count_cut      = { fg = "#000000", bg = "#ea6962" }
count_selected = { fg = "#000000", bg = "#e6a0b3" }

# Border
border_symbol = "│"
border_style  = { fg = "#6c6666" }

# Highlighting
syntect_theme = "~/.config/yazi/bat-theme/Gruvbox-N.tmTheme"
# syntect_theme = "~/.config/yazi/bat-theme/Catppuccin-macchiato.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3c3937", bg = "#3c3937" }

# Mode
mode_normal = { fg = "#000000", bg = "#A89984", bold = true }
mode_select = { fg = "#000000", bg = "#d3869b", bold = true }
mode_unset  = { fg = "#000000", bg = "#8bca4b", bold = true }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#A89984", bg = "#000000" }
progress_error  = { fg = "#ea6962", bg = "#000000" }

# Permissions
permissions_t = { fg = "#8bca4b" }
permissions_r = { fg = "#ea6962" }
permissions_w = { fg = "#cfc251" }
permissions_x = { fg = "#7daea3" }
permissions_s = { fg = "#619b63" }

# Owner

# : }}}


# : Select {{{

[select]
border   = { fg = "#7daea3" }
active   = { fg = "#d3869b" }
inactive = {}

# : }}}


# : Input {{{

[input]
border   = { fg = "#8bca4b" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


[notify]
title_info  = { fg = "#7daea3" }
title_warn  = { fg = "#d3869b" }
title_error = { fg = "#ea6962" }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""


# : Completion {{{

[completion]
border   = { fg = "#8bca4b" }
active   = { bg = "#3c3937" }
inactive = {}

# Icons
icon_file    = ""
icon_folder  = "󰝰"
icon_command = ""

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#FFAA00" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#000000" }
cand            = { fg = "#99e0d1" }
rest            = { fg = "#3c3937" }
desc            = { fg = "#f598b0" }
separator       = "  "
separator_style = { fg = "#d3d3ce" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#8bca4b" }
run    = { fg = "#e98d8d" }
desc    = { fg = "#EC8C1F" }
hovered = { bg = "#3c3937", bold = true }
footer  = { fg = "#000000", bg = "#EC8C1F" }

# : }}}
[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#EC8C1F" },

	# Videos
	{ mime = "video/*", fg = "#8bca4b" },
	{ mime = "application/octet-stream", fg = "#8bca4b" },
	{ mime = "video/MP2T", fg = "#8bca4b" },
	{ mime = "application/vnd.rn-realmedia", fg = "#8bca4b" },
	{ mime = "audio/*", fg = "#71acc8" },

	# Archives
	{ mime = "application/zip", fg = "#e98d8d" },
	{ mime = "application/gzip", fg = "#e98d8d" },
	{ mime = "application/x-bzip", fg = "#e98d8d" },
	{ mime = "application/x-bzip2", fg = "#e98d8d" },
	{ mime = "application/x-tar", fg = "#e98d8d" },
	{ mime = "application/x-7z-compressed", fg = "#e98d8d" },
	{ mime = "application/x-rar", fg = "#e98d8d" },
	{ mime = "inode/directory", fg = "#d5af6d" },
	{ mime = "text/x-script.python", fg = "#cd98f3" },
	{ mime = "text/x-shellscript", fg = "#cd98f3" },
	{ mime = "text/x-c", fg = "#cd98f3" },
	{ mime = "text/x-c++", fg = "#cd98f3" },
	{ mime = "text/x-lua", fg = "#cd98f3" },
	{ mime = "text/x-go", fg = "#cd98f3" },
	{ mime = "text/x-rs", fg = "#cd98f3" },
	{ mime = "text/javascript", fg = "#cd98f3" },
	{ mime = "text/css", fg = "#cd98f3" },
	{ mime = "text/scss", fg = "#cd98f3" },
	{ mime = "text/html", fg = "#cd98f3" },
	{ mime = "text/x-lisp", fg = "#cd98f3" },
	{ mime = "text/x-perl", fg = "#cd98f3" },
	{ mime = "text/setting", fg = "#a3cc43" },
	{ mime = "application/json", fg = "#a3cc43" },
	{ mime = "application/x-pie-executable", fg = "#36bb4e" },
	{ mime = "application/epub+zip", fg = "#c5cc43" },
	{ mime = "application/x-mobipocket-ebook", fg = "#c5cc43" },

	# Fallback
	{ name = "*", fg = "#c5bf98" },
	{ name = "*/", fg = "#d5af6d" }
]

[icon]

rules = [
	# Programming
	{ name = "*.c"    , text = "", fg = "#599eff" },
	{ name = "*.cpp"  , text = "", fg = "#519aba" },
	{ name = "*.class", text = "", fg = "#cc3e44" },
	{ name = "*.cs"   , text = "󰌛", fg = "#596706" },
	{ name = "*.css"  , text = "", fg = "#42a5f5" },
	{ name = "*.elm"  , text = "", fg = "#4391d2" },
	{ name = "*.fish" , text = "", fg = "#4d5a5e" },
	{ name = "*.go"   , text = "", fg = "#519aba" },
	{ name = "*.h"    , text = "", fg = "#a074c4" },
	{ name = "*.hpp"  , text = "", fg = "#a074c4" },
	{ name = "*.html" , text = "", fg = "#e44d26" },
	{ name = "*.jar"  , text = "", fg = "#cc3e44" },
	{ name = "*.java" , text = "", fg = "#cc3e44" },
	{ name = "*.js"   , text = "", fg = "#F1F134" },
	{ name = "*.jsx"  , text = "", fg = "#20c2e3" },
	{ name = "*.lua"  , text = "", fg = "#51a0cf" },
	{ name = "*.nix"  , text = "", fg = "#7ebae4" },
	{ name = "*.nu"   , text = ">", fg = "#3aa675" },
	{ name = "*.php"  , text = "", fg = "#a074c4" },
	{ name = "*.py"   , text = "", fg = "#ffbc03" },
	{ name = "*.rb"   , text = "", fg = "#701516" },
	{ name = "*.rs"   , text = "", fg = "#dea584" },
	{ name = "*.sbt"  , text = "", fg = "#4d5a5e" },
	{ name = "*.scala", text = "", fg = "#cc463e" },
	{ name = "*.scss" , text = "", fg = "#f55385" },
	{ name = "*.sh"   , text = "", fg = "#a2c5d1" },
	{ name = "*.swift", text = "", fg = "#e37933" },
	{ name = "*.ts"   , text = "", fg = "#519aba" },
	{ name = "*.tsx"  , text = "", fg = "#1354bf" },
	{ name = "*.vim"  , text = "", fg = "#019833" },
	{ name = "*.vue"  , text = "󰡄", fg = "#8dc149" },

	# Text
	{ name = "*.conf", text = "", fg = "#6d8086" },
	{ name = "*.ini" , text = "", fg = "#6d8086" },
	{ name = "*.json", text = "", fg = "#cbcb41" },
	{ name = "*.kdl" , text = "", fg = "#6d8086" },
	{ name = "*.md"  , text = "", fg = "#ffffff" },
	{ name = "*.toml", text = "", fg = "#ffffff" },
	{ name = "*.txt" , text = "", fg = "#89e051" },
	{ name = "*.yaml", text = "", fg = "#6d8086" },
	{ name = "*.yml" , text = "", fg = "#6d8086" },

	# Archives
	{ name = "*.7z" , text = "", fg = "#be8be8" },
	{ name = "*.bz2", text = "", fg = "#be8be8" },
	{ name = "*.gz" , text = "", fg = "#be8be8" },
	{ name = "*.rar", text = "", fg = "#be8be8" },
	{ name = "*.tar", text = "", fg = "#be8be8" },
	{ name = "*.xz" , text = "", fg = "#be8be8" },
	{ name = "*.zip", text = "", fg = "#be8be8" },
	{ name = "*.tgz", text = "", fg = "#be8be8" },

	# Images
	{ name = "*.HEIC", text = "󰋹", fg = "#FD971F" },
	{ name = "*.avif", text = "󰋹", fg = "#FD971F" },
	{ name = "*.bmp" , text = "󰋹", fg = "#FD971F" },
	{ name = "*.gif" , text = "󰋹", fg = "#FD971F" },
	{ name = "*.ico" , text = "󰋹", fg = "#cbcb41" },
	{ name = "*.jpeg", text = "󰋹", fg = "#FD971F" },
	{ name = "*.jpg" , text = "󰋹", fg = "#FD971F" },
	{ name = "*.png" , text = "󰋹", fg = "#FD971F" },
	{ name = "*.svg" , text = "󰋹", fg = "#FFB13B" },
	{ name = "*.webp", text = "󰋹", fg = "#FD971F" },

	# Movies
	{ name = "*.avi" , text = "󱜅", fg = "#89e051" },
	{ name = "*.mkv" , text = "󱜅", fg = "#89e051" },
	{ name = "*.mov" , text = "󱜅", fg = "#89e051" },
	{ name = "*.mp4" , text = "󱜅", fg = "#89e051" },
	{ name = "*.webm", text = "󱜅", fg = "#89e051" },
	
	# Audio
	{ name = "*.aac" , text = "", fg = "#66D8EF" },
	{ name = "*.flac", text = "", fg = "#66D8EF" },
	{ name = "*.m4a" , text = "", fg = "#66D8EF" },
	{ name = "*.mp3" , text = "", fg = "#66D8EF" },
	{ name = "*.ogg" , text = "", fg = "#66D8EF" },
	{ name = "*.wav" , text = "", fg = "#66D8EF" },


	# Documents
	{ name = "*.csv" , text = "", fg = "#89e051" },
	{ name = "*.doc" , text = "", fg = "#185abd" },
	{ name = "*.doct", text = "", fg = "#185abd" },
	{ name = "*.docx", text = "", fg = "#185abd" },
	{ name = "*.dot" , text = "", fg = "#185abd" },
	{ name = "*.ods" , text = "", fg = "#207245" },
	{ name = "*.ots" , text = "", fg = "#207245" },
	{ name = "*.pdf" , text = "", fg = "#b30b00" },
	{ name = "*.pom" , text = "", fg = "#cc3e44" },
	{ name = "*.pot" , text = "", fg = "#cb4a32" },
	{ name = "*.potx", text = "", fg = "#cb4a32" },
	{ name = "*.ppm" , text = "", fg = "#a074c4" },
	{ name = "*.ppmx", text = "", fg = "#cb4a32" },
	{ name = "*.pps" , text = "", fg = "#cb4a32" },
	{ name = "*.ppsx", text = "", fg = "#cb4a32" },
	{ name = "*.ppt" , text = "", fg = "#cb4a32" },
	{ name = "*.pptx", text = "", fg = "#cb4a32" },
	{ name = "*.xlc" , text = "", fg = "#207245" },
	{ name = "*.xlm" , text = "", fg = "#207245" },
	{ name = "*.xls" , text = "", fg = "#207245" },
	{ name = "*.xlsm", text = "", fg = "#207245" },
	{ name = "*.xlsx", text = "", fg = "#207245" },
	{ name = "*.xlt" , text = "", fg = "#207245" },

	# Lockfiles
	{ name = "*.lock", text = "", fg = "#bbbbbb" },

	# Misc
	{ name = "*.bin", text = "", fg = "#9F0500" },
	{ name = "*.exe", text = "", fg = "#9F0500" },
	{ name = "*.pkg", text = "", fg = "#9F0500" },

	# Dotfiles
	{ name = ".DS_Store"     , text = "", fg = "#41535b" },
	{ name = ".bashprofile"  , text = "", fg = "#89e051" },
	{ name = ".bashrc"       , text = "", fg = "#89e051" },
	{ name = ".gitattributes", text = "", fg = "#41535b" },
	{ name = ".gitignore"    , text = "", fg = "#41535b" },
	{ name = ".gitmodules"   , text = "", fg = "#41535b" },
	{ name = ".vimrc"        , text = "", fg = "#019833" },
	{ name = ".zprofile"     , text = "", fg = "#89e051" },
	{ name = ".zshenv"       , text = "", fg = "#89e051" },
	{ name = ".zshrc"        , text = "", fg = "#89e051" },


	# book
	{ name = "*.epub"     , text = "󱗖", fg = "#cbcb41"},
	{ name = "*.mobi"     , text = "󱗖", fg = "#cbcb41"},
	{ name = "*.desktop"  , text = "", fg = "#cbcb41"},
	{ name = "Makefile"  ,  text = "", fg = "#cbcb41"},
	{ name = "meson.build"  ,  text = "", fg = "#cbcb41"},
	{ name = "*.xml"  ,  text = "󰗀", fg = "#89e051"},
	{ name = "config.mk"  ,  text = "", fg = "#cbcb41"},
	{ name = "*.yuck"  ,  text = "󰰳", fg = "#89e051"},

	# Named files
	{ name = "COPYING"      , text = "󰿃", fg = "#cbcb41" },
	{ name = "Containerfile", text = "󰡨", fg = "#458ee6" },
	{ name = "Dockerfile"   , text = "󰡨", fg = "#458ee6" },
	{ name = "LICENSE"      , text = "󰿃", fg = "#d0bf41" },

	# Directories
	# { name = ".config/"    , text = "" },
	# { name = ".git/"       , text = "" },
	# { name = "Desktop/"    , text = "" },
	# { name = "Development/", text = "" },
	# { name = "Documents/"  , text = "" },
	# { name = "down/"  , text = "" },
	# { name = "Library/"    , text = "" },
	# { name = "Movies/"     , text = "" },
	# { name = "Music/"      , text = "" },
	# { name = "Pictures/"   , text = "" },
	# { name = "Public/"     , text = "" },
	# { name = "video/"     , text = "" },

	# Default
	{ name = "*" , text = "" },
	{ name = "*/", text = "󰝰", fg = "#F7C030" },
]
